---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoservice
  template:
    metadata:
      labels:
        app: geoservice
    spec:
      containers:
      - name: geoservice
        image: aaseper/geoservice:v1
---
apiVersion: v1
kind: Service
metadata:
  name: geoservice
spec:
  type: ClusterIP
  selector:
    app: geoservice
  ports:
  -  port: 8008
---
