---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-deployment
  template:
    metadata:
      labels:
        app: server-deployment
    spec:
      containers:
      - name: server-deployment
        image: aaseper/server:v1
        env:
        - name: DATABASE_HOST
          value: db
        - name: DATABASE_PORT
          value: "3306"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://db/default_schema
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: pass
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server-deployment
  ports:
  - port: 8443
    targetPort: 8443
    nodePort: 30001
---
