---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windservice
  template:
    metadata:
      labels:
        app: windservice
    spec:
      containers:
      - name: windservice
        image: aaseper/windservice:v1
---
apiVersion: v1
kind: Service
metadata:
  name: windservice
spec:
  type: ClusterIP
  selector:
    app: windservice
  ports:
  - port: 9090
---
